title: Centre d'assistance Slack
locale: fr_FR

permalink: pretty

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  collections:
    output: true
  sections:
    output: true
  articles:
    output: true

defaults:
  - 
    scope:
      type: articles
    values:
      layout: article
  - 
    scope:
      type: collections
    values:
      layout: collection

plugins:
  - jekyll-relative-links
  - jekyll-menus
  - jekyll-seo-tag
  
relative_links:
  enabled: true
  collections: true
